"""
agents/analyzer.py — Analyzer Agent（电路语义分析师）

Phase 0 的第一个 Agent。职责：
1. 从网表构建图 → Louvain 聚类生成模块划分初稿
2. LLM 校正模块划分（合并/拆分/重命名/去耦电容归属修正）
3. 输出增强网表（器件角色、信号类型、模块划分、模块间连接）
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field

from agents.base_agent import BaseAgent
from agents.netlist_graph import build_netlist_graph, cluster_louvain

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# 增强网表数据结构
# ---------------------------------------------------------------------------

@dataclass
class EnrichedComponent:
    """增强后的器件信息"""
    ref: str
    value: str
    role: str               # decoupling_cap / core_ic / feedback_resistor / ...
    module_id: str
    priority: str = "normal"  # critical / normal / low


@dataclass
class EnrichedModule:
    """增强后的模块信息"""
    module_id: str
    module_name: str
    module_type: str          # power_ldo / power_buck / mcu_core / sensor / ...
    core_component: str       # 核心器件 ref
    components: list[str]
    layout_template_hint: str = ""  # ldo_standard / crystal / decap_cluster / ...
    notes: str = ""


@dataclass
class ModuleConnection:
    """模块间连接"""
    from_module: str
    to_module: str
    net_names: list[str]
    total_weight: int
    placement_constraint: str = ""  # adjacent_tight / moderate / flexible


@dataclass
class EnrichedNetlist:
    """增强网表 — Analyzer 的最终输出"""
    components: list[EnrichedComponent]
    modules: list[EnrichedModule]
    connections: list[ModuleConnection]
    board_type: str = ""          # mixed_signal / digital / power / rf
    total_components: int = 0
    total_modules: int = 0


# ---------------------------------------------------------------------------
# Analyzer Agent
# ---------------------------------------------------------------------------

_ANALYZER_SYSTEM_PROMPT = """\
You are an expert PCB Analyzer Agent. Your task is to refine a preliminary module partition \
generated by a graph clustering algorithm, and enrich it with circuit semantic information.

You will receive:
1. A list of components with their values
2. A preliminary module partition from Louvain clustering
3. The netlist (connections between components)

Your job:
- Rename modules with meaningful names (e.g., "3V3_LDO", "MCU_Core", "USB_Interface")
- Identify the core component of each module
- Suggest a layout_template_hint if a well-known pattern applies (ldo_standard, crystal, decap_cluster, force_directed)
- Fix misassigned decoupling capacitors: they belong to the IC they serve, not to a power module
- Merge modules that are too small (1-2 components) into related modules
- Annotate each component's role (core_ic, decoupling_cap, bulk_cap, feedback_resistor, pull_up, crystal, load_cap, led_indicator, voltage_divider, esd_protection, connector, etc.)
- Identify inter-module connections and their relative importance
- Identify the board type (digital, mixed_signal, power, rf, etc.)

Respond in JSON with this exact structure:
{
  "board_type": "string",
  "modules": [
    {
      "module_id": "M01",
      "module_name": "string",
      "module_type": "string",
      "core_component": "ref",
      "components": ["ref1", "ref2"],
      "layout_template_hint": "string or empty",
      "notes": "string"
    }
  ],
  "component_roles": [
    {"ref": "U1", "role": "core_ic", "priority": "critical"}
  ],
  "connections": [
    {
      "from_module": "M01",
      "to_module": "M02",
      "net_names": ["VCC", "SPI_CLK"],
      "total_weight": 5,
      "placement_constraint": "adjacent_tight"
    }
  ]
}
"""


class AnalyzerAgent(BaseAgent):
    """
    Analyzer Agent：读懂电路，生成增强网表。

    使用步骤：
        analyzer = AnalyzerAgent()
        result = analyzer.analyze(components, nets)
    """

    def __init__(self, model: str = "deepseek-chat"):
        super().__init__(
            name="Analyzer",
            system_prompt=_ANALYZER_SYSTEM_PROMPT,
            model=model,
        )

    def analyze(
        self,
        components: list[dict],
        nets: list[dict],
        resolution: float = 1.0,
    ) -> EnrichedNetlist:
        """
        执行完整的分析流程。

        components: [{"ref": "U1", "value": "ESP32", ...}, ...]
        nets: [{"name": "VCC", "nodes": ["U1.1", "C1.1"]}, ...]
        resolution: Louvain 分辨率（越大模块越多越小）

        返回 EnrichedNetlist。
        """
        # Step 1: 图聚类
        logger.info("[Analyzer] Step 1: Building netlist graph and running Louvain...")
        G = build_netlist_graph(nets)
        clusters = cluster_louvain(G, resolution=resolution)

        cluster_summary = []
        for c in clusters:
            cluster_summary.append({
                "module_id": c.module_id,
                "components": c.components,
                "size": len(c.components),
            })

        # Step 2: LLM 校正
        logger.info("[Analyzer] Step 2: LLM enrichment...")
        comp_summary = []
        for c in components:
            comp_summary.append({
                "ref": c.get("ref", ""),
                "value": c.get("value", ""),
            })

        net_summary = []
        for n in nets:
            name = n.get("name", "")
            if name.upper() in ("GND", ""):
                continue
            net_summary.append({
                "name": name,
                "nodes": n.get("nodes", []),
            })

        user_prompt = (
            f"## Components ({len(comp_summary)} total)\n"
            f"{json.dumps(comp_summary, ensure_ascii=False)}\n\n"
            f"## Preliminary Module Partition (Louvain)\n"
            f"{json.dumps(cluster_summary, ensure_ascii=False)}\n\n"
            f"## Netlist ({len(net_summary)} nets, GND excluded)\n"
            f"{json.dumps(net_summary, ensure_ascii=False)}\n\n"
            "Please refine the partition and enrich with semantic information."
        )

        llm_result = self.run_json(user_prompt)

        # Step 3: 解析 LLM 输出为 EnrichedNetlist
        return self._parse_llm_result(llm_result, components)

    def _parse_llm_result(
        self,
        llm_result: dict,
        original_components: list[dict],
    ) -> EnrichedNetlist:
        """解析 LLM JSON 输出为 EnrichedNetlist"""
        # 解析模块
        modules = []
        for m in llm_result.get("modules", []):
            modules.append(EnrichedModule(
                module_id=m.get("module_id", ""),
                module_name=m.get("module_name", ""),
                module_type=m.get("module_type", ""),
                core_component=m.get("core_component", ""),
                components=m.get("components", []),
                layout_template_hint=m.get("layout_template_hint", ""),
                notes=m.get("notes", ""),
            ))

        # 解析器件角色
        role_map = {}
        for cr in llm_result.get("component_roles", []):
            role_map[cr.get("ref", "")] = (
                cr.get("role", "unknown"),
                cr.get("priority", "normal"),
            )

        # 构建 module_id 映射
        ref_to_module = {}
        for m in modules:
            for ref in m.components:
                ref_to_module[ref] = m.module_id

        # 构建 EnrichedComponent 列表
        enriched_comps = []
        for c in original_components:
            ref = c.get("ref", "")
            role, priority = role_map.get(ref, ("unknown", "normal"))
            enriched_comps.append(EnrichedComponent(
                ref=ref,
                value=c.get("value", ""),
                role=role,
                module_id=ref_to_module.get(ref, "unassigned"),
                priority=priority,
            ))

        # 解析模块间连接
        connections = []
        for conn in llm_result.get("connections", []):
            connections.append(ModuleConnection(
                from_module=conn.get("from_module", ""),
                to_module=conn.get("to_module", ""),
                net_names=conn.get("net_names", []),
                total_weight=conn.get("total_weight", 0),
                placement_constraint=conn.get("placement_constraint", ""),
            ))

        # 验证：检查是否所有器件都被分配到了模块
        assigned_refs = {ref for m in modules for ref in m.components}
        all_refs = {c.get("ref", "") for c in original_components}
        unassigned = all_refs - assigned_refs - {""}
        if unassigned:
            logger.warning("[Analyzer] %d components not assigned to any module: %s",
                           len(unassigned), sorted(unassigned)[:10])

        return EnrichedNetlist(
            components=enriched_comps,
            modules=modules,
            connections=connections,
            board_type=llm_result.get("board_type", "unknown"),
            total_components=len(enriched_comps),
            total_modules=len(modules),
        )
